export default {
  welcomeText: 'Hoşgeldin,',

  monday: 'Pazartesi',
  tuesday: 'Salı',
  wednesday: 'Çarşamba',
  thursday: 'Perşembe',
  friday: 'Cuma',
  saturday: 'Cumartesi',
  sunday: 'Pazar',

  january: 'Ocak',
  february: 'Şubat',
  march: 'Mart',
  april: 'Nisan',
  may: 'Mayıs',
  june: 'Haziran',
  july: 'Temmuz',
  august: 'Ağustos',
  september: 'Eylül',
  october: 'Ekim',
  november: 'Kasım',
  december: 'Aralık',

  connectedDevices: 'BAĞLI CİHAZLAR',

  homeIconName: 'home',
  workPlaceIconName: 'work_place',
  depotIconName: 'depot',

  vehicleTrackingIconName: 'VEHICLE_TRACKING',
  fireIconName: 'FIRE',
  cameraIconName: 'CAMERA',
  IvidionBridgeIconName: 'IVIDEON_BRIDGE',
  ipCameraIconName: 'IP_CAMERA',
  nvrIconName: 'NVR',
  accessControlIconName: 'ACCESS_CONTROL',
  panelIconName: 'PANEL',
  smartPanelIconName: 'SMART_PANEL',
  smartboxIoModuleIconName: 'SMARTBOX_IO_MODULE',
  smartHubIconName: 'SMARTHUB',

  noDeviceTitle: 'CİHAZ YOK',
  noDeviceExplanation: 'Eklenmiş cihazınız bulunmamaktadır',
  newDeviceRequest: 'YENİ CİHAZ TALEBİ',
  deviceRequests: 'CİHAZ TALEPLERİ',
};
